### ISSUE TITLE
Add a Cosignatory crashes the app

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#243]
If I want to add a cosignatory and put in the address by copy & paste, there would not show up the address to tab on it [picture one]. (only if i delete the last character). The problem is, that the app crashes immediatelly if you add the address as cosignatory [picture two], because is doesn't look up the public key.
Can there shown up a message which says "please insert a known address or public key of the cosignatory"

![photo-2016-06-14-16-17-50_2217](https://cloud.githubusercontent.com/assets/17567386/16046501/f35e5524-324c-11e6-9769-e34f14833661.PNG)

![photo-2016-06-14-16-13-29_2216](https://cloud.githubusercontent.com/assets/17567386/16046515/fd6cee86-324c-11e6-8ab6-bce0fb1d6c3c.PNG)
Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by jabo38** [comment]
1.  We need it to not crash
2. We need a good message for the error

**Comment by LyubomirDominik** [comment]
Fix issue with crash

Fixed in Version 2 Build 40

**Comment by jabo38** [comment]
tried to add via name for an address I own in my address book and has a known public key.  I start to type the name, the app suggests it, I click on the name, the app crashes.

**Comment by LyubomirDominik** [comment]
Remove accounts from address book and reinstall app. And try again.
Account is broken, they was created in old versions or manually

**Comment by jabo38** [comment]
removing accounts from address book and deleting app and reinstall does not fix the issue.  

as I mentioned earlier there are two problems. 

1) pasting in an address causes the app to crash
2) there is no alert

**Comment by LyubomirDominik** [comment]
#230

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 9ac177c41f27ead6a0e79143864227e16a9d8fa2fd78cf13e4f8f37fddf9b054
